### ISSUE TITLE
Все include должны быть объявлены в самом верху

### ISSUE THREAD

**Issue by kinda-neat** [AlexeyCheremnykh/task-2.1#12]

**Comment by AlexeyCheremnykh** [comment]
Исправил

**Comment by chmnkh** [comment]
Исправил

**Comment by kinda-neat** [comment]
Вот здесь предпочтительно тоже инклюдить миксины и вызывать их
![2018-03-02 13-23-20](https://user-images.githubusercontent.com/27883524/36886051-f41be9dc-1e1c-11e8-89dc-39ccc8a09c90.png)
