### ISSUE TITLE
Вынести в отдельные блоки содержимое skills и software

### ISSUE THREAD

**Issue by kinda-neat** [AlexeyCheremnykh/task-2.1#14]
В skills и в software соответственно, нужно вынести элементы в отдельные блоки, потому что здесь структура одна и та же, меняется только содержимое
![2018-03-02 13-38-27](https://user-images.githubusercontent.com/27883524/36886452-095257bc-1e1f-11e8-8fc4-ce62c16f0ca0.png)
![2018-03-02 13-38-34](https://user-images.githubusercontent.com/27883524/36886453-097d28f2-1e1f-11e8-9491-51d89e8753fa.png)

**Comment by chmnkh** [comment]
Исправил
