### ISSUE TITLE
applicant-competence — название от одного примера применения, а должно быть общее

### ISSUE THREAD

**Issue by Znack** [AlexeyCheremnykh/task-2.1#18]
Так как все равно блок исопльзуется для представляения разной по семантике информации, название лучше дать общее, которое отражает какой класс информации отображается, чтобы в этот класс входили все примеры использований :)

**Comment by chmnkh** [comment]
Один пример применения - это подразумевается применение в рамках данного макета, или один из двух способов применения блока на макете (в experience и в education)? Т.е. нужно сделать такое название, чтобы не только для макета подходило, верно?

**Comment by Znack** [comment]
Ну в идеале название да, должно не только для макета подходить, но пока что хватит и такого абстрактного названия, чтобы и  experience и education нормально смотрелись в контексте этого применения :)

**Comment by chmnkh** [comment]
Более абстрактно сделал.
Не идеально, но вроде бы более менее норм.
