### ISSUE TITLE
Вопрос про responsive

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-2.1#2]
При уменьшении экрана так и запланировано, что мы имеем большой (в плане размера шрифта) заголовок, не вмещающийся на одну строку, и маленький абзац?
![image](https://user-images.githubusercontent.com/26929933/36135688-4c36ef60-10bf-11e8-95e1-b31099c0b3a7.png)

**Comment by chmnkh** [comment]
По поводу размеров шрифтов: да, там все размеры возвращаются к изначальным (при ширине от 1116px), а правая колонка просто под левую становится.
По поводу переноса даты на новую строку: в этом я ничего критичного не увидел. Размер шрифта там менять тоже не очень по-моему, потому что в этом макете вообще если где-то размер шрифта просто изменить, а размеры всего остального вокруг (оступы, всякие кружки, полоски, шрифты) не менять, то будет коряво выглядеть. Т.е. если менять размер шрифта в заголовке, то по-моему нужно тогда вообще размеры всего в макете менять, а при данной ширине экрана тогда все мелкое будет. 
Вообще можно было бы в принципе слеши перед датой через псевдо-элемент делать например, а потом при какой-то ширине их убирать и дату на новую строку переносить. Сделать так, или все таки оставить как есть?

**Comment by Zarwlar** [comment]
Здесь чисто вопрос вкусовщины. Мне кажется, что заголовок ну очень уж большой по сравнению с текстом, который в абзаце. Но если ты так не считаешь, то можешь закрывать ишус

**Comment by chmnkh** [comment]
Ну там по-моему вообще к макету вопросов достаточно, а пропорции я никакие не менял, поэтому оставлю так и закрою)
