### ISSUE TITLE
Изменить SOFTWARE

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-2.1#3]
Нужно продумать более гибкую систему и реализовать её касательно добавления новых прогресс-баров. Сейчас у тебя там хардкод)

**Comment by Zarwlar** [comment]
Всё сказанное выше справедливо и для блока skills

**Comment by chmnkh** [comment]
Этот ишью как и все остальные закрывать после исправления, или ждать подтверждения какого-то?

**Comment by Zarwlar** [comment]
Да эти я сам закрою) Я действительно не ту ветку смотрел, потому  что смотрел через сайт гитхаба (легко зайти на master и не заметить), в рефакторинге действительно всё это исправлено

**Comment by Zarwlar** [comment]
Но почему осталось число 12?)

`        - for (let i = 0; i < 12 - level; i++)`

**Comment by chmnkh** [comment]
Исправил
