### ISSUE TITLE
Способы передачи данных в функцию

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-2.1#5]
Почитай про способы передачи данных в функцию (этот вопрос есть на собеседовании), чтобы не делать штуки вроде таких)
`+skills(3, 4, 5, 6)`

**Comment by chmnkh** [comment]
Стоп, это же из master ветки код, а в refactoring ветке там по-другому:
`+cv-skills({creative: 3, teamwork: 4, innovate: 5, communication: 6})`
Я это еще малость поменяю для ишью #3, но это так, чтобы сказать, что ты походу не ту ветку смотрел вообще) Ну либо я не так сделал, хотя в задании вроде бы сказано, что во время рефакторинга все в другую ветку надо коммитить.
