### ISSUE TITLE
Вынести параметры блоков в отдельный файл

### ISSUE THREAD

**Issue by kinda-neat** [AlexeyCheremnykh/task-2.1#9]

**Comment by chmnkh** [comment]
Исправил

**Comment by kinda-neat** [comment]
Ты же мог просто сделать require json файла и получить оттуда тот же самый data.applicant, data.profile ... и т.д.

**Comment by kinda-neat** [comment]
npm run server
![2018-03-03 09-49-25](https://user-images.githubusercontent.com/27883524/36929766-2f99025a-1ec8-11e8-8452-dc1a43ae48f4.png)
![2018-03-03 09-49-55](https://user-images.githubusercontent.com/27883524/36929772-416a3896-1ec8-11e8-9b45-e4167d0ccc42.png)

**Comment by chmnkh** [comment]
Вроде пофиксил, у себя проверил, норм.

**Comment by chmnkh** [comment]
Исправил.
Название ласт коммита зафейлил и не сослался на ишью. Ссылка на него: https://github.com/AlexeyCheremnykh/task-2.1/commit/a42e6b6b65513c31ec82d85a7d0874b60ba62473

**Comment by Geksanit** [comment]
Ссылаться на ишью можно в комментариях коммита, и вообще везде. 
npm run server  проверил - работает. Закрывай ишью.
